### ISSUE TITLE
wrong point of in-page link

### ISSUE THREAD

**Issue by Mister-Kin** [sfire/scbm#1]
1）https://docs.blender.org/manual/zh-hans/dev/video_editing/sequencer/introduction.html
2）modified一词的页内链接指向错误，指向了</video_editing/sequencer/selecting>。
3）
![Snipaste_2019-08-10_12-23-10](https://user-images.githubusercontent.com/34863761/62817524-ed14c680-bb6a-11e9-96ea-0f651e032744.png)

4）将链接修改为</video_editing/sequencer/editing>。

**Comment by tiankuan913588** [comment]
好奇怎么回事，核查发现原版英文版就已经出错了，问题压根不是汉化组引起的

**Comment by sfire** [comment]
这个[原文我已经改过来了](https://developer.blender.org/rBM5699)。译文的话，这两天我会手动抓一次po。

**Comment by sfire** [comment]
译文已同步修正 https://developer.blender.org/rBMT3846
