### ISSUE TITLE
VSE/片段属性页面错误

### ISSUE THREAD

**Issue by Mister-Kin** [sfire/scbm#11]
[VSE/片段属性页面链接](https://docs.blender.org/manual/en/dev/video_editing/sequencer/properties/strip.html)
###  错误一：调整面板/[视频]小节-Reverse功能内容过时
描述：内容已过时，相应功能已更改为Playback Direction。
错误段落截图：
![Snipaste_2019-08-21_01-05-46](https://user-images.githubusercontent.com/34863761/63368174-f9412500-c3af-11e9-9a2b-cc8297e77d67.png)
对应UI截图：
![Snipaste_2019-08-21_01-06-31](https://user-images.githubusercontent.com/34863761/63368235-183fb700-c3b0-11e9-9a43-e3346827123d.png)
**修改建议：重新编写该项内容。**
### 错误二：调整面板/[视频]小节-Deinterlace功能内容位置错误
描述：位置错误，该功能已不在[video]区域，转移至[source]面板。
错误段落截图：
![Snipaste_2019-08-21_01-16-25](https://user-images.githubusercontent.com/34863761/63368857-5ee1e100-c3b1-11e9-8c06-9f253a6b91ec.png)
对应UI截图：
![Snipaste_2019-08-21_01-16-09](https://user-images.githubusercontent.com/34863761/63368868-6608ef00-c3b1-11e9-938e-ecb5ea02322d.png)
**修改建议：把Deinterlace内容转移至[source]面板，位置在[Resolution]功能之上。**
### 错误三：调整面板/[视频]小节-X/Y镜像功能内容过时且位置错误 。
描述：内容过时而且不在[video]区域。相应功能已合并为镜像功能，并且已转移至调整面板[transform]区域。
错误段落截图：
![Snipaste_2019-08-21_01-24-53](https://user-images.githubusercontent.com/34863761/63369670-fe53a380-c3b2-11e9-83fc-019cd2e9f450.png)
对应UI截图：
![Snipaste_2019-08-21_01-25-21](https://user-images.githubusercontent.com/34863761/63369702-162b2780-c3b3-11e9-814f-65dc7fa1c44a.png)
**修改建议：重新编写该项内容，并将内容转移至调整面板/[transform]小节，位置在[Image Offset]功能之上。**
### 错误四：调整面板/[声音]小节-Mute (speaker icon)屏蔽功能已去除。
描述：该项功能已去除，改用片段属性面板标题栏中的屏蔽功能来实现屏蔽。
错误段落截图：
![Snipaste_2019-08-21_01-36-46](https://user-images.githubusercontent.com/34863761/63370480-dbc28a00-c3b4-11e9-9f0d-4b1da5f2ad82.png)
对应UI截图：
![Snipaste_2019-08-21_01-38-20](https://user-images.githubusercontent.com/34863761/63370486-e0873e00-c3b4-11e9-859c-1167b4152299.png)
**修改建议：删除该项功能描述。**
### 错误五：源面板/[Change Data/Files]功能菜单内容错误。
错误段落截图：
![Snipaste_2019-08-21_01-44-48](https://user-images.githubusercontent.com/34863761/63370933-baae6900-c3b5-11e9-86c0-ff844f2c726f.png)
对应UI截图：
![Snipaste_2019-08-21_01-45-36](https://user-images.githubusercontent.com/34863761/63370948-c306a400-c3b5-11e9-91f3-c8db6d647435.png)
**修改建议：将菜单内容Strip ‣ Inputs ‣ Paths/files修正为Strip ‣ Inputs ‣ Change Paths/files。**

**Comment by sfire** [comment]
原文已全部修正 [rBM5781](https://developer.blender.org/rBM5781)
