### ISSUE TITLE
物理->流体模拟->流体类型->控制，缺失“吸引半径”条目

### ISSUE THREAD

**Issue by KassadinL** [sfire/scbm#12]
[https://docs.blender.org/manual/en/latest/physics/fluid/types/control.html#options](url)

原文“Attraction Force”下，缺少“Radius”条目

<img width="301" alt="Annotation 2019-08-23 103551" src="https://user-images.githubusercontent.com/19602109/63562947-f7cf5280-c591-11e9-8438-a6901dc1a5b6.png">
<img width="545" alt="Annotation 2019-08-23 103700" src="https://user-images.githubusercontent.com/19602109/63562949-faca4300-c591-11e9-8ff6-6821a2884212.png">

**Comment by sfire** [comment]
https://developer.blender.org/rBM5998
已修正
