### ISSUE TITLE
蜡笔->模式->绘制->工具设置->填充，链接错误

### ISSUE THREAD

**Issue by KassadinL** [sfire/scbm#16]
[https://docs.blender.org/manual/en/dev/grease_pencil/modes/draw/tool_settings/fill.html#boundary-strokes](url)

链接错误，此段最后一行 *清理* 工具在蜡笔菜单下，不在笔画菜单。
<img width="578" alt="Annotation 2019-08-27 082708" src="https://user-images.githubusercontent.com/19602109/63732015-bba73500-c8a4-11e9-9e87-477bc547ba84.png">

**Comment by sfire** [comment]
已全部修正 [rBM5781](https://developer.blender.org/rBM5781)
