### ISSUE TITLE
有点怪异的翻译错误

### ISSUE THREAD

**Issue by tiankuan913588** [sfire/scbm#19]
editors/uv/introduction.html
UV 解释
下面第二段开头
如果你拿剪刀盒子的接缝,你将能够把它展开在桌子上。
有点不知所云，参考2.79的翻译editors/uv_image/uv/overview.html，发现一直翻译有点问题
原文是
If you were to take a pair of scissors and cut a seam or fold of the box, you would be able to lay it flat on a tabletop
or或明显漏掉，只是2.79语句通顺，没有注意到问题
大意应该是 拿一把剪子沿接缝或者褶痕裁开盒子,你将能够把它展开在桌子上

**Comment by sfire** [comment]
这里的译文是有些问题，已经做了[调整](https://developer.blender.org/rBMT3958)。
