### ISSUE TITLE
键盘快捷键标签露出来

### ISSUE THREAD

**Issue by tiankuan913588** [sfire/scbm#2]
interface/controls/buttons/eyedropper.html
最后一行
kbd:Spacebar 重置并重新开始混合颜色。
kbd:Spacebar 那处翻译误操作，删掉前边那个“：”导致标签问题

**Comment by tiankuan913588** [comment]
interface/controls/templates/color_ramp.html
吸管工具（吸管图标）:kbd:E 翻译漏掉前边空格

**Comment by tiankuan913588** [comment]
interface/tool_system.html
有些工具有操纵杆（比如*Shear* 和 Spin）以协助使用。
Shear前边漏掉一个空格，导致标签问题

它上方
 每个工具都有自己的快捷键，以取代使用 LMB 选择工具的方式，有时也需要使用组合快捷键，在*设置修改-键位映射*
漏掉一个空格 并且翻译怪怪？
原文 Key-maps can be edited from the preferences
估计官方写文档那个人表述有点问题
应该是
 *键位映射*  能够从 *设置...* 编辑  注意空格 之类 preferences-》UI那边当前翻译是设置...

**Comment by sfire** [comment]
以上问题均已修正后提交
