### ISSUE TITLE
VSE/序列编辑器/片段/速度控制片段页面错误

### ISSUE THREAD

**Issue by Mister-Kin** [sfire/scbm#20]
[VSE/序列编辑器/片段/速度控制片段页面链接](https://docs.blender.org/manual/en/dev/video_editing/sequencer/strips/effects/speed_control.html)
### 错误一：Use as Speed选项功能已去除
描述：该项功能已去除。
错误段落截图：
![Snipaste_2019-09-03_23-15-47](https://user-images.githubusercontent.com/34863761/64187186-c2d0d300-cea2-11e9-9cf5-e8fcfe132fb7.png)
对应UI截图：
![Snipaste_2019-09-03_23-05-16](https://user-images.githubusercontent.com/34863761/64187206-c9f7e100-cea2-11e9-8a28-8139b8af22d0.png)
**修改建议：删除该项功能描述。**
### 错误二：Frame Number选项功能已去除
描述：该项功能已去除。
错误段落截图：
![Snipaste_2019-09-03_23-13-08](https://user-images.githubusercontent.com/34863761/64187215-cebc9500-cea2-11e9-91f5-ba01fd0ba130.png)
对应UI截图：
![Snipaste_2019-09-03_23-05-16](https://user-images.githubusercontent.com/34863761/64187206-c9f7e100-cea2-11e9-8a28-8139b8af22d0.png)
**修改建议：删除该项功能描述。**
### 错误三：示例内的两个例子的相关内容已过时
描述：两个例子使用到上述提到的已去除的选项功能。
错误段落截图：
![Snipaste_2019-09-03_23-27-19](https://user-images.githubusercontent.com/34863761/64187277-ec89fa00-cea2-11e9-96fa-050cc7563757.png)
修改建议：重新编写示例内容。

**Comment by sfire** [comment]
![图片](https://user-images.githubusercontent.com/5409756/70768850-08eeda00-1da2-11ea-9634-65d3801c6a44.png)
这一页没错，你取消勾选 **拉伸到导入片段长度** 试试。
