### ISSUE TITLE
原文快捷键错误

### ISSUE THREAD

**Issue by tiankuan913588** [sfire/scbm#22]
editors/timeline.html
播放控制 -》倒放 Shift-Alt-A，实际上是Shift-Alt-spacebar
播放 Alt-A，实际上是spacebar

/editors/graph_editor/fcurves/editing.html
镜像 Shift-M，实际上是Ctrl-M
采样和烘焙关键帧-》采样关键帧Shift-O，实际上是Shift-Alt-O，顺便提醒一下，Sample Keyframes的Sample，UI那边翻译为取样

**Comment by tiankuan913588** [comment]
editors/nla/introduction.html
这个页面对比UI，发现快捷键原文丢失，导致中文版也丢失了
从上到下
设置预览区间 P
清空预览区间 Alt+P
自动选择预览区间 shift-Ctrl+P
全部 A
反转 Ctrl+I
框选 B
轴向框选 Alt+B
当前帧之前 [
当前帧之后 ]
扩展 E
缩放 S
复制 shift+D
关联副本 Alt+D
分离片段 Y
删除片段 X
切换静默 H
应用缩放 Ctrl+A
缩放归零 Alt+S
单一化 U
交换片段 Alt+F
上移片段 Page Up
下移片段 Page Down
开始编辑暂存的动作 Shift+Tab
开始调节片段动作 Tab
添加动作片段 Shift+A
添加过渡 Shift+T
添加声音片段 Shift+K
添加复合片段 Ctrl+G
移除复合片段 Ctr+Altl+G

**Comment by tiankuan913588** [comment]
editors/text_editor.html
视图菜单-》侧栏 原文错误
快捷键不可能是N，因为如果是n，变成直接在文本中输入n，必然是组合键
应该是Ctrl+T

**Comment by sfire** [comment]
https://developer.blender.org/rBM5998
已全部修正
