### ISSUE TITLE
有点怪异的翻译问题

### ISSUE THREAD

**Issue by tiankuan913588** [sfire/scbm#23]
/editors/graph_editor/fcurves/modifiers.html
封套-》最小值 最大值
默认影响下参考值为 1:1 的较低的距离。
1:1 默认影响的参考值的上限距离。
觉得奇怪，发现原文只是把Lower换成Upper，所以按理说不至于把1:1的位置从中间移动到前边
把两种翻译结合一下
默认影响的参考值为``1:1``的下限距离。
默认影响的参考值为``1:1``的上限距离。
下方 点-》帧-》最小值 最大值 疑似同一个问题
把Lower-》下限，Upper-》上限 看起来正常点

**Comment by tiankuan913588** [comment]
scene_layout/object/selecting.html
镜像选择 下方
例如，"sword.L" 和 "剑.R"
sword就是剑，要不不要翻译，要不两个一起翻译
也许"sword.L" 和 "sword.R"还好一点，因为原文此处意思是sword的左右两个物体

**Comment by sfire** [comment]
https://developer.blender.org/rBMT4318
已修正
