### ISSUE TITLE
翻译打错字

### ISSUE THREAD

**Issue by bqdong** [sfire/scbm#26]
https://docs.blender.org/manual/zh-hans/latest/advanced/blender_directory_layout.html#blender-directory-layout
![image-20200919104313606](https://user-images.githubusercontent.com/52027654/93657552-518c9f80-fa66-11ea-9499-f244e4fc8966.png)
“Blender目录布局”这个标题下面的：这需要用词自行在 LOCAL 目录创建名为 config 的文件夹。
应该是：这需要**用户**自行在 LOCAL 目录创建名为 config 的文件夹。
英文原文是This requires you to create a folder named config in the LOCAL directory.

**Comment by sfire** [comment]
已修正
https://developer.blender.org/rBMT5320
