### ISSUE TITLE
VSE/编辑页面错误【原文错误】

### ISSUE THREAD

**Issue by Mister-Kin** [sfire/scbm#4]
以下错误的页面链接均为[VSE/编辑页面](https://docs.blender.org/manual/en/latest/video_editing/sequencer/editing.html)
## 错误 1 - 小节【吸附片段】菜单子项描述错误： Strip ‣ Snap Strips
截图：
![Snipaste_2019-08-14_00-09-59](https://user-images.githubusercontent.com/34863761/62958347-19f60180-be29-11e9-9062-a95ace507eef.png)
**修改建议：** 将Strip ‣ Snap Strips修正为Strip ‣ Transform ‣ Snap Strips to Playhead
## 错误 2 - 小节【吸附片段】正文错误：vertical green line
错误描述：原文说cursor为垂直绿线，但依照Blender 2.8的默认主题配色，cursor应该为垂直蓝线。
截图：
![Snipaste_2019-08-14_00-20-07](https://user-images.githubusercontent.com/34863761/62958462-50338100-be29-11e9-8972-ade91188ec15.png)
**修改建议：** 将vertical green line修正为vertical blue line。同时原文使用cursor，直译便是光标，本人觉得会造成理解困难，建议直接将cursor修改为playhead更好理解。
## 错误 3 - 小节【清除片段偏移量】菜单子项位置错误：Strip ‣ Clear Strips Offset
截图：
![Snipaste_2019-08-14_00-36-12](https://user-images.githubusercontent.com/34863761/62959515-925dc200-be2b-11e9-8d3c-78f6c4b5dc43.png)
**修改建议：** 将Strip ‣ Clear Strips Offset修正为Strip ‣ Transform ‣ Clear Strips Offset
## 错误 4 - 小节【复制片段】菜单子项描述错误：Strip ‣ Duplicate
截图：
![Snipaste_2019-08-14_00-40-40](https://user-images.githubusercontent.com/34863761/62959981-46f7e380-be2c-11e9-8baa-cffd591bf2aa.png)
**修改建议：** 将Strip ‣ Duplicate修正为Strip ‣ Duplicate Strips
## 错误 5 - 小节【删除片段】快捷键缺少：Hotkey: Delete
截图：
![Snipaste_2019-08-14_00-47-06](https://user-images.githubusercontent.com/34863761/62960428-35fba200-be2d-11e9-8931-7d19f3377504.png)
**修改建议：** 将Hotkey: Delete补充为Hotkey: Delete/X
## 错误 6 - 小节【分离图像】菜单描述多余：Strip ‣ Movie Strip ‣ Separate Images
错误描述：Blender 2.8中UI中里没有该子项菜单。
截图：
![Snipaste_2019-08-14_00-50-50](https://user-images.githubusercontent.com/34863761/62960671-c33ef680-be2d-11e9-8a9b-09e68cdc39a8.png)
**修改建议：** 删除该子项菜单描述，保留快捷键描述。
## 错误 7 - 小节【重新指定输入项】菜单描述多余：Strip ‣ Effect Strip ‣ Reassign Inputs
错误描述：Blender 2.8中UI中里没有该子项菜单。
截图：
![Snipaste_2019-08-14_00-58-53](https://user-images.githubusercontent.com/34863761/62961107-b7076900-be2e-11e9-90ee-3d1b6d34bd53.png)
**修改建议：** 删除该子项菜单描述，保留快捷键描述。

**Comment by sfire** [comment]
**分离图像** 操作是存在的:
![图片](https://user-images.githubusercontent.com/5409756/62971769-2c7e3400-be45-11e9-99cb-474a8eecd658.png)
其他菜单均已修正 https://developer.blender.org/rBM5702
**重新指定输入项** 确实是在菜单里无法找到的，查找操作也找不到，不知道是取消了，还是改头换面了。

**Comment by Mister-Kin** [comment]
1）哦，对，我忘了只有在加载图像片段时才会正确加载 **分离图像** 操作菜单。这么说来，**分离图像** 菜单确实存在，只是菜单位置描述错误而已。
2）实际上错误7中的 **重新指定输入项** 操作是存在的，只是未能在菜单里找到。
该操作可在快捷键映射表里查找到：
![02](https://user-images.githubusercontent.com/34863761/62987565-fb1c5d00-be72-11e9-9600-012be4c58453.png)

**Comment by sfire** [comment]
![image](https://user-images.githubusercontent.com/5409756/62988933-ab409480-be78-11e9-84fc-59241db203f9.png)
**重新指定输入项** 也有，需要添加效果片断才有。

**Comment by Mister-Kin** [comment]
OK，怪我不仔细，都忘了应该有对应场景才会加载菜单。又得把原文改回来，麻烦老哥了。 @sfire

**Comment by sfire** [comment]
原文已修正 https://developer.blender.org/rBM5704
