### ISSUE TITLE
两处有点奇怪的翻译错误

### ISSUE THREAD

**Issue by tiankuan913588** [sfire/scbm#5]
editors/3dview/modes.html
物体模式列表
下面 那个Draw Mode应该是绘制模式，而不是 权重绘制模式，涉及当前没有完整翻译的蜡笔章节，应该没有权重什么事

上方
可以修改整个编辑器的行为, 比如 UV辑器 和 3D视图
Editor翻译成辑器，估计是打漏字，应该是编辑器

**Comment by sfire** [comment]
已修正 https://developer.blender.org/rBMT3858
