### ISSUE TITLE
VSE/复合片段页面错误【原文错误】

### ISSUE THREAD

**Issue by Mister-Kin** [sfire/scbm#6]
1）错误页面链接[VSE/复合片段页面](https://docs.blender.org/manual/en/dev/video_editing/sequencer/meta.html)
2）快捷键错误： **UnMeta Strip** 操作的快捷键错误： Alt-G
3）截图：
![Snipaste_2019-08-15_01-22-20](https://user-images.githubusercontent.com/34863761/63042477-a45b6580-befc-11e9-8fb5-0efa62f6b4ae.png)
4）修改建议：将快捷键修正为Ctrl-Alt-G。

**Comment by sfire** [comment]
原文已修正 https://developer.blender.org/rBM5711
译文已修正 https://developer.blender.org/rBMT3864
