### ISSUE TITLE
VSE/导航页面错误

### ISSUE THREAD

**Issue by Mister-Kin** [sfire/scbm#7]
1）错误页面链接：[VSE/导航页面](https://docs.blender.org/manual/en/dev/video_editing/sequencer/navigating.html)
2）描述：四个错误位于【导航】小节，错误类型相同。都是操作与描述内容相反。
3）截图：
![Snipaste_2019-08-16_17-03-40](https://user-images.githubusercontent.com/34863761/63156847-2dcb7e80-c048-11e9-9677-c4aa6654d37b.png)
4）修改建议：
两两相互交换描述内容，即按顺序，分别将四个内容描述句子修正为：
---
* Current frame will jump to beginning of strip.
* Current frame will jump to end of strip.
---
* Jump to previous center of the strip.
* Jump to next center of the strip.
---

**Comment by sfire** [comment]
原文已修正 https://developer.blender.org/rBM5725
译文已修正 https://developer.blender.org/rBMT3873
